
spring.application.name=Ems
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#.............(Hibernate ko batata hai ki kaunsa database use ho raha hai.)........

spring.jpa.hibernate.ddl-auto=update
 #............(Hibernate entities ko dekhkar database schema manage karta hai.)...............

# ................SQL queries console me dikhengi........................
spring.jpa.show-sql=true

# ....................SQL queries properly formatted hongi..........................
spring.jpa.properties.hibernate.format_sql=true
